Imports System
Imports System.Collections.Generic
Imports System.Linq
Imports System.Web
Imports System.Data.Entity

Public Class SampleData
    Inherits DropCreateDatabaseIfModelChanges(Of MusicStoreEntities)
    Protected Overrides Sub Seed(ByVal context As MusicStoreEntities)
        Dim genres = New List(Of Genre) From {
         New Genre With {.Name = "Rock"},
         New Genre With {.Name = "Jazz"},
         New Genre With {.Name = "Metal"},
         New Genre With {.Name = "Alternative"},
         New Genre With {.Name = "Disco"},
         New Genre With {.Name = "Blues"},
         New Genre With {.Name = "Latin"},
         New Genre With {.Name = "Reggae"},
         New Genre With {.Name = "Pop"},
         New Genre With {.Name = "Classical"}}

        Dim artists = New List(Of Artist) From {
         New Artist With {.Name = "Aaron Copland & London Symphony Orchestra"},
         New Artist With {.Name = "Aaron Goldberg"},
         New Artist With {.Name = "AC/DC"},
         New Artist With {.Name = "Accept"},
         New Artist With {.Name = "Adrian Leaper & Doreen de Feis"},
         New Artist With {.Name = "Aerosmith"},
         New Artist With {.Name = "Aisha Duo"},
         New Artist With {.Name = "Alanis Morissette"},
         New Artist With {.Name = "Alberto Turco & Nova Schola Gregoriana"},
         New Artist With {.Name = "Alice In Chains"},
         New Artist With {.Name = "Amy Winehouse"},
         New Artist With {.Name = "Anita Ward"},
         New Artist With {.Name = "Antônio Carlos Jobim"},
         New Artist With {.Name = "Apocalyptica"},
         New Artist With {.Name = "Audioslave"},
         New Artist With {.Name = "Barry Wordsworth & BBC Concert Orchestra"},
         New Artist With {.Name = "Berliner Philharmoniker & Hans Rosbaud"},
         New Artist With {.Name = "Berliner Philharmoniker & Herbert Von Karajan"},
         New Artist With {.Name = "Billy Cobham"},
         New Artist With {.Name = "Black Label Society"},
         New Artist With {.Name = "Black Sabbath"},
         New Artist With {.Name = "Boston Symphony Orchestra & Seiji Ozawa"},
         New Artist With {.Name = "Britten Sinfonia, Ivor Bolton & Lesley Garrett"},
         New Artist With {.Name = "Bruce Dickinson"},
         New Artist With {.Name = "Buddy Guy"},
         New Artist With {.Name = "Caetano Veloso"},
         New Artist With {.Name = "Cake"},
         New Artist With {.Name = "Calexico"},
         New Artist With {.Name = "Cássia Eller"},
         New Artist With {.Name = "Chic"},
         New Artist With {.Name = "Chicago Symphony Orchestra & Fritz Reiner"},
         New Artist With {.Name = "Chico Buarque"},
         New Artist With {.Name = "Chico Science & Nação Zumbi"},
         New Artist With {.Name = "Choir Of Westminster Abbey & Simon Preston"},
         New Artist With {.Name = "Chris Cornell"},
         New Artist With {.Name = "Christopher O'Riley"},
         New Artist With {.Name = "Cidade Negra"},
         New Artist With {.Name = "Cláudio Zoli"},
         New Artist With {.Name = "Creedence Clearwater Revival"},
         New Artist With {.Name = "David Coverdale"},
         New Artist With {.Name = "Deep Purple"},
         New Artist With {.Name = "Dennis Chambers"},
         New Artist With {.Name = "Djavan"},
         New Artist With {.Name = "Donna Summer"},
         New Artist With {.Name = "Dread Zeppelin"},
         New Artist With {.Name = "Ed Motta"},
         New Artist With {.Name = "Edo de Waart & San Francisco Symphony"},
         New Artist With {.Name = "Elis Regina"},
         New Artist With {.Name = "English Concert & Trevor Pinnock"},
         New Artist With {.Name = "Eric Clapton"},
         New Artist With {.Name = "Eugene Ormandy"},
         New Artist With {.Name = "Faith No More"},
         New Artist With {.Name = "Falamansa"},
         New Artist With {.Name = "Foo Fighters"},
         New Artist With {.Name = "Frank Zappa & Captain Beefheart"},
         New Artist With {.Name = "Fretwork"},
         New Artist With {.Name = "Funk Como Le Gusta"},
         New Artist With {.Name = "Gerald Moore"},
         New Artist With {.Name = "Gilberto Gil"},
         New Artist With {.Name = "Godsmack"},
         New Artist With {.Name = "Gonzaguinha"},
         New Artist With {.Name = "Göteborgs Symfoniker & Neeme Järvi"},
         New Artist With {.Name = "Guns N' Roses"},
         New Artist With {.Name = "Gustav Mahler"},
         New Artist With {.Name = "Incognito"},
         New Artist With {.Name = "Iron Maiden"},
         New Artist With {.Name = "James Levine"},
         New Artist With {.Name = "Jamiroquai"},
         New Artist With {.Name = "Jimi Hendrix"},
         New Artist With {.Name = "Joe Satriani"},
         New Artist With {.Name = "Jorge Ben"},
         New Artist With {.Name = "Jota Quest"},
         New Artist With {.Name = "Judas Priest"},
         New Artist With {.Name = "Julian Bream"},
         New Artist With {.Name = "Kent Nagano and Orchestre de l'Opéra de Lyon"},
         New Artist With {.Name = "Kiss"},
         New Artist With {.Name = "Led Zeppelin"},
         New Artist With {.Name = "Legião Urbana"},
         New Artist With {.Name = "Lenny Kravitz"},
         New Artist With {.Name = "Les Arts Florissants & William Christie"},
         New Artist With {.Name = "London Symphony Orchestra & Sir Charles Mackerras"},
         New Artist With {.Name = "Luciana Souza/Romero Lubambo"},
         New Artist With {.Name = "Lulu Santos"},
         New Artist With {.Name = "Marcos Valle"},
         New Artist With {.Name = "Marillion"},
         New Artist With {.Name = "Marisa Monte"},
         New Artist With {.Name = "Martin Roscoe"},
         New Artist With {.Name = "Maurizio Pollini"},
         New Artist With {.Name = "Mela Tenenbaum, Pro Musica Prague & Richard Kapp"},
         New Artist With {.Name = "Men At Work"},
         New Artist With {.Name = "Metallica"},
         New Artist With {.Name = "Michael Tilson Thomas & San Francisco Symphony"},
         New Artist With {.Name = "Miles Davis"},
         New Artist With {.Name = "Milton Nascimento"},
         New Artist With {.Name = "Mötley Crüe"},
         New Artist With {.Name = "Motörhead"},
         New Artist With {.Name = "Nash Ensemble"},
         New Artist With {.Name = "Nicolaus Esterhazy Sinfonia"},
         New Artist With {.Name = "Nirvana"},
         New Artist With {.Name = "O Terço"},
         New Artist With {.Name = "Olodum"},
         New Artist With {.Name = "Orchestra of The Age of Enlightenment"},
         New Artist With {.Name = "Os Paralamas Do Sucesso"},
         New Artist With {.Name = "Ozzy Osbourne"},
         New Artist With {.Name = "Page & Plant"},
         New Artist With {.Name = "Paul D'Ianno"},
         New Artist With {.Name = "Pearl Jam"},
         New Artist With {.Name = "Pink Floyd"},
         New Artist With {.Name = "Queen"},
         New Artist With {.Name = "R.E.M."},
         New Artist With {.Name = "Raul Seixas"},
         New Artist With {.Name = "Red Hot Chili Peppers"},
         New Artist With {.Name = "Roger Norrington, London Classical Players"},
         New Artist With {.Name = "Royal Philharmonic Orchestra & Sir Thomas Beecham"},
         New Artist With {.Name = "Rush"},
         New Artist With {.Name = "Santana"},
         New Artist With {.Name = "Scholars Baroque Ensemble"},
         New Artist With {.Name = "Scorpions"},
         New Artist With {.Name = "Sergei Prokofiev & Yuri Temirkanov"},
         New Artist With {.Name = "Sir Georg Solti & Wiener Philharmoniker"},
         New Artist With {.Name = "Skank"},
         New Artist With {.Name = "Soundgarden"},
         New Artist With {.Name = "Spyro Gyra"},
         New Artist With {.Name = "Stevie Ray Vaughan & Double Trouble"},
         New Artist With {.Name = "Stone Temple Pilots"},
         New Artist With {.Name = "System Of A Down"},
         New Artist With {.Name = "Temple of the Dog"},
         New Artist With {.Name = "Terry Bozzio, Tony Levin & Steve Stevens"},
         New Artist With {.Name = "The 12 Cellists of The Berlin Philharmonic"},
         New Artist With {.Name = "The Black Crowes"},
         New Artist With {.Name = "The Cult"},
         New Artist With {.Name = "The Doors"},
         New Artist With {.Name = "The King's Singers"},
         New Artist With {.Name = "The Police"},
         New Artist With {.Name = "The Posies"},
         New Artist With {.Name = "The Rolling Stones"},
         New Artist With {.Name = "The Who"},
         New Artist With {.Name = "Tim Maia"},
         New Artist With {.Name = "Ton Koopman"},
         New Artist With {.Name = "U2"},
         New Artist With {.Name = "UB40"},
         New Artist With {.Name = "Van Halen"},
         New Artist With {.Name = "Various Artists"},
         New Artist With {.Name = "Velvet Revolver"},
         New Artist With {.Name = "Vinícius De Moraes"},
         New Artist With {.Name = "Wilhelm Kempff"},
         New Artist With {.Name = "Yehudi Menuhin"},
         New Artist With {.Name = "Yo-Yo Ma"},
         New Artist With {.Name = "Zeca Pagodinho"}}

        Dim TempList = New List(Of Album)() From {
         New Album With {.Title = "The Best Of Men At Work", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Men At Work"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "A Copland Celebration, Vol. I", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Aaron Copland & London Symphony Orchestra"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Worlds", .Genre = genres.Single(Function(g) g.Name = "Jazz"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Aaron Goldberg"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "For Those About To Rock We Salute You", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "AC/DC"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Let There Be Rock", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "AC/DC"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Balls to the Wall", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Accept"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Restless and Wild", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Accept"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Górecki: Symphony No. 3", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Adrian Leaper & Doreen de Feis"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Big Ones", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Aerosmith"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Quiet Songs", .Genre = genres.Single(Function(g) g.Name = "Jazz"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Aisha Duo"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Jagged Little Pill", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Alanis Morissette"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Facelift", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Alice In Chains"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Frank", .Genre = genres.Single(Function(g) g.Name = "Pop"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Amy Winehouse"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Ring My Bell", .Genre = genres.Single(Function(g) g.Name = "Disco"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Anita Ward"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Chill: Brazil (Disc 2)", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Antônio Carlos Jobim"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Warner 25 Anos", .Genre = genres.Single(Function(g) g.Name = "Jazz"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Antônio Carlos Jobim"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Plays Metallica By Four Cellos", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Apocalyptica"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Revelations", .Genre = genres.Single(Function(g) g.Name = "Alternative"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Audioslave"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Audioslave", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Audioslave"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "The Last Night of the Proms", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Barry Wordsworth & BBC Concert Orchestra"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Sibelius: Finlandia", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Berliner Philharmoniker & Hans Rosbaud"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Mozart: Symphonies Nos. 40 & 41", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Berliner Philharmoniker & Herbert Von Karajan"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "The Best Of Billy Cobham", .Genre = genres.Single(Function(g) g.Name = "Jazz"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Billy Cobham"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Alcohol Fueled Brewtality Live! [Disc 1]", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Black Label Society"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Alcohol Fueled Brewtality Live! [Disc 2]", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Black Label Society"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Black Sabbath Vol. 4 (Remaster)", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Black Sabbath"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Black Sabbath", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Black Sabbath"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Carmina Burana", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Boston Symphony Orchestra & Seiji Ozawa"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "A Soprano Inspired", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Britten Sinfonia, Ivor Bolton & Lesley Garrett"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Chemical Wedding", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Bruce Dickinson"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Prenda Minha", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Caetano Veloso"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Sozinho Remix Ao Vivo", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Caetano Veloso"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Cake: B-Sides and Rarities", .Genre = genres.Single(Function(g) g.Name = "Alternative"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Cake"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Carried to Dust (Bonus Track Version)", .Genre = genres.Single(Function(g) g.Name = "Alternative"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Calexico"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Cássia Eller - Sem Limite [Disc 1]", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Cássia Eller"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Le Freak", .Genre = genres.Single(Function(g) g.Name = "Disco"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Chic"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Scheherazade", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Chicago Symphony Orchestra & Fritz Reiner"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Minha Historia", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Chico Buarque"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Afrociberdelia", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Chico Science & Nação Zumbi"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Da Lama Ao Caos", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Chico Science & Nação Zumbi"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Carry On", .Genre = genres.Single(Function(g) g.Name = "Alternative"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Chris Cornell"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "SCRIABIN: Vers la flamme", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Christopher O'Riley"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Acústico MTV [Live]", .Genre = genres.Single(Function(g) g.Name = "Reggae"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Cidade Negra"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Cidade Negra - Hits", .Genre = genres.Single(Function(g) g.Name = "Reggae"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Cidade Negra"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Na Pista", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Cláudio Zoli"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Chronicle, Vol. 1", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Creedence Clearwater Revival"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Chronicle, Vol. 2", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Creedence Clearwater Revival"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Into The Light", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "David Coverdale"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Come Taste The Band", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Deep Purple"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Deep Purple In Rock", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Deep Purple"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Fireball", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Deep Purple"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Machine Head", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Deep Purple"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "MK III The Final Concerts [Disc 1]", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Deep Purple"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Purpendicular", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Deep Purple"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Slaves And Masters", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Deep Purple"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Stormbringer", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Deep Purple"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "The Battle Rages On", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Deep Purple"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "The Final Concerts (Disc 2)", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Deep Purple"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Outbreak", .Genre = genres.Single(Function(g) g.Name = "Jazz"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Dennis Chambers"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Djavan Ao Vivo - Vol. 02", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Djavan"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Djavan Ao Vivo - Vol. 1", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Djavan"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "MacArthur Park Suite", .Genre = genres.Single(Function(g) g.Name = "Disco"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Donna Summer"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Un-Led-Ed", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Dread Zeppelin"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "The Best of Ed Motta", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Ed Motta"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Adams, John: The Chairman Dances", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Edo de Waart & San Francisco Symphony"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Elis Regina-Minha História", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Elis Regina"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Pachelbel: Canon & Gigue", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "English Concert & Trevor Pinnock"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Unplugged", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Eric Clapton"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "The Cream Of Clapton", .Genre = genres.Single(Function(g) g.Name = "Blues"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Eric Clapton"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Unplugged", .Genre = genres.Single(Function(g) g.Name = "Blues"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Eric Clapton"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Respighi:Pines of Rome", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Eugene Ormandy"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Strauss: Waltzes", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Eugene Ormandy"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "King For A Day Fool For A Lifetime", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Faith No More"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Deixa Entrar", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Falamansa"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "In Your Honor [Disc 1]", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Foo Fighters"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "In Your Honor [Disc 2]", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Foo Fighters"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "The Colour And The Shape", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Foo Fighters"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Bongo Fury", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Frank Zappa & Captain Beefheart"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Roda De Funk", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Funk Como Le Gusta"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Quanta Gente Veio Ver (Live)", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Gilberto Gil"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Quanta Gente Veio ver--Bônus De Carnaval", .Genre = genres.Single(Function(g) g.Name = "Jazz"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Gilberto Gil"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Faceless", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Godsmack"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Meus Momentos", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Gonzaguinha"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Nielsen: The Six Symphonies", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Göteborgs Symfoniker & Neeme Järvi"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Appetite for Destruction", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Guns N' Roses"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Use Your Illusion I", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Guns N' Roses"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Use Your Illusion II", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Guns N' Roses"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Blue Moods", .Genre = genres.Single(Function(g) g.Name = "Jazz"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Incognito"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "A Matter of Life and Death", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Iron Maiden"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Brave New World", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Iron Maiden"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Fear Of The Dark", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Iron Maiden"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Live At Donington 1992 (Disc 1)", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Iron Maiden"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Live At Donington 1992 (Disc 2)", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Iron Maiden"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Rock In Rio [CD2]", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Iron Maiden"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "The Number of The Beast", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Iron Maiden"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "The X Factor", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Iron Maiden"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Virtual XI", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Iron Maiden"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "A Real Dead One", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Iron Maiden"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "A Real Live One", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Iron Maiden"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Live After Death", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Iron Maiden"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "No Prayer For The Dying", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Iron Maiden"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Piece Of Mind", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Iron Maiden"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Powerslave", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Iron Maiden"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Rock In Rio [CD1]", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Iron Maiden"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Rock In Rio [CD2]", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Iron Maiden"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Seventh Son of a Seventh Son", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Iron Maiden"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Somewhere in Time", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Iron Maiden"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "The Number of The Beast", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Iron Maiden"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Iron Maiden", .Genre = genres.Single(Function(g) g.Name = "Blues"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Iron Maiden"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Mascagni: Cavalleria Rusticana", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "James Levine"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Emergency On Planet Earth", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Jamiroquai"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Are You Experienced?", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Jimi Hendrix"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Surfing with the Alien (Remastered)", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Joe Satriani"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Jorge Ben Jor 25 Anos", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Jorge Ben"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Jota Quest-1995", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Jota Quest"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Living After Midnight", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Judas Priest"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Weill: The Seven Deadly Sins", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Kent Nagano and Orchestre de l'Opéra de Lyon"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Greatest Kiss", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Kiss"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Unplugged [Live]", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Kiss"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "BBC Sessions [Disc 1] [Live]", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Led Zeppelin"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "BBC Sessions [Disc 2] [Live]", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Led Zeppelin"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Coda", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Led Zeppelin"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Houses Of The Holy", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Led Zeppelin"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "In Through The Out Door", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Led Zeppelin"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "IV", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Led Zeppelin"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Led Zeppelin I", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Led Zeppelin"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Led Zeppelin II", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Led Zeppelin"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Led Zeppelin III", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Led Zeppelin"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Physical Graffiti [Disc 1]", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Led Zeppelin"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Physical Graffiti [Disc 2]", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Led Zeppelin"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Presence", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Led Zeppelin"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "The Song Remains The Same (Disc 1)", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Led Zeppelin"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "The Song Remains The Same (Disc 2)", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Led Zeppelin"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Mais Do Mesmo", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Legião Urbana"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Greatest Hits", .Genre = genres.Single(Function(g) g.Name = "Reggae"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Lenny Kravitz"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Greatest Hits", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Lenny Kravitz"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Greatest Hits", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Lenny Kravitz"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Tchaikovsky: The Nutcracker", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "London Symphony Orchestra & Sir Charles Mackerras"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Duos II", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Luciana Souza/Romero Lubambo"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Chill: Brazil (Disc 1)", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Marcos Valle"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Misplaced Childhood", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Marillion"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Barulhinho Bom", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Marisa Monte"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Szymanowski: Piano Works, Vol. 1", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Martin Roscoe"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "...And Justice For All", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Metallica"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Black Album", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Metallica"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Garage Inc. (Disc 1)", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Metallica"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Garage Inc. (Disc 2)", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Metallica"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Load", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Metallica"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Master Of Puppets", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Metallica"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "ReLoad", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Metallica"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Ride The Lightning", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Metallica"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "St. Anger", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Metallica"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Berlioz: Symphonie Fantastique", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Michael Tilson Thomas & San Francisco Symphony"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Prokofiev: Romeo & Juliet", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Michael Tilson Thomas & San Francisco Symphony"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Miles Ahead", .Genre = genres.Single(Function(g) g.Name = "Jazz"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Miles Davis"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "The Essential Miles Davis [Disc 1]", .Genre = genres.Single(Function(g) g.Name = "Jazz"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Miles Davis"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "The Essential Miles Davis [Disc 2]", .Genre = genres.Single(Function(g) g.Name = "Jazz"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Miles Davis"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Milton Nascimento Ao Vivo", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Milton Nascimento"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Minas", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Milton Nascimento"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Motley Crue Greatest Hits", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Mötley Crüe"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Ace Of Spades", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Motörhead"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Mozart: Chamber Music", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Nash Ensemble"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "The Best of Beethoven", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Nicolaus Esterhazy Sinfonia"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Nevermind", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Nirvana"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Compositores", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "O Terço"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Olodum", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Olodum"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Bach: The Brandenburg Concertos", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Orchestra of The Age of Enlightenment"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Acústico MTV", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Os Paralamas Do Sucesso"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Arquivo II", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Os Paralamas Do Sucesso"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Arquivo Os Paralamas Do Sucesso", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Os Paralamas Do Sucesso"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Tribute", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Ozzy Osbourne"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Bark at the Moon (Remastered)", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Ozzy Osbourne"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Blizzard of Ozz", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Ozzy Osbourne"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Diary of a Madman (Remastered)", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Ozzy Osbourne"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "No More Tears (Remastered)", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Ozzy Osbourne"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Speak of the Devil", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Ozzy Osbourne"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Walking Into Clarksdale", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Page & Plant"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "The Beast Live", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Paul D'Ianno"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Live On Two Legs [Live]", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Pearl Jam"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Riot Act", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Pearl Jam"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Ten", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Pearl Jam"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Vs.", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Pearl Jam"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Dark Side Of The Moon", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Pink Floyd"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Greatest Hits I", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Queen"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Greatest Hits II", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Queen"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "News Of The World", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Queen"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "New Adventures In Hi-Fi", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "R.E.M."), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Raul Seixas", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Raul Seixas"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "By The Way", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Red Hot Chili Peppers"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Californication", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Red Hot Chili Peppers"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Purcell: The Fairy Queen", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Roger Norrington, London Classical Players"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Haydn: Symphonies 99 - 104", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Royal Philharmonic Orchestra & Sir Thomas Beecham"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Retrospective I (1974-1980)", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Rush"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Santana - As Years Go By", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Santana"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Santana Live", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Santana"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Supernatural", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Santana"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Handel: The Messiah (Highlights)", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Scholars Baroque Ensemble"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Prokofiev: Symphony No.1", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Sergei Prokofiev & Yuri Temirkanov"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Wagner: Favourite Overtures", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Sir Georg Solti & Wiener Philharmoniker"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Maquinarama", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Skank"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "O Samba Poconé", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Skank"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "A-Sides", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Soundgarden"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Heart of the Night", .Genre = genres.Single(Function(g) g.Name = "Jazz"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Spyro Gyra"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Morning Dance", .Genre = genres.Single(Function(g) g.Name = "Jazz"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Spyro Gyra"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "In Step", .Genre = genres.Single(Function(g) g.Name = "Blues"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Stevie Ray Vaughan & Double Trouble"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Core", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Stone Temple Pilots"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Mezmerize", .Genre = genres.Single(Function(g) g.Name = "Metal"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "System Of A Down"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Temple of the Dog", .Genre = genres.Single(Function(g) g.Name = "Alternative"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Temple of the Dog"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "[1997] Black Light Syndrome", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Terry Bozzio, Tony Levin & Steve Stevens"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "South American Getaway", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "The 12 Cellists of The Berlin Philharmonic"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Live [Disc 1]", .Genre = genres.Single(Function(g) g.Name = "Blues"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "The Black Crowes"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Live [Disc 2]", .Genre = genres.Single(Function(g) g.Name = "Blues"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "The Black Crowes"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Beyond Good And Evil", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "The Cult"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "The Doors", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "The Doors"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "English Renaissance", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "The King's Singers"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "The Police Greatest Hits", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "The Police"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Every Kind of Light", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "The Posies"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Hot Rocks, 1964-1971 (Disc 1)", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "The Rolling Stones"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "No Security", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "The Rolling Stones"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Voodoo Lounge", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "The Rolling Stones"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "My Generation - The Very Best Of The Who", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "The Who"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Serie Sem Limite (Disc 1)", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Tim Maia"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Serie Sem Limite (Disc 2)", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Tim Maia"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Bach: Toccata & Fugue in D Minor", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Ton Koopman"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Achtung Baby", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "U2"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "B-Sides 1980-1990", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "U2"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "How To Dismantle An Atomic Bomb", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "U2"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Pop", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "U2"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Rattle And Hum", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "U2"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "The Best Of 1980-1990", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "U2"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "War", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "U2"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Zooropa", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "U2"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "UB40 The Best Of - Volume Two [UK]", .Genre = genres.Single(Function(g) g.Name = "Reggae"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "UB40"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Diver Down", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Van Halen"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "The Best Of Van Halen, Vol. I", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Van Halen"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Van Halen III", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Van Halen"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Van Halen", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Van Halen"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Axé Bahia 2001", .Genre = genres.Single(Function(g) g.Name = "Pop"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Various Artists"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Sambas De Enredo 2001", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Various Artists"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Vozes do MPB", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Various Artists"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Contraband", .Genre = genres.Single(Function(g) g.Name = "Rock"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Velvet Revolver"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Vinicius De Moraes", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Vinícius De Moraes"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Bach: Goldberg Variations", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Wilhelm Kempff"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Bartok: Violin & Viola Concertos", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Yehudi Menuhin"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Bach: The Cello Suites", .Genre = genres.Single(Function(g) g.Name = "Classical"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Yo-Yo Ma"), .AlbumArtUrl = "/Content/Images/placeholder.gif"},
         New Album With {.Title = "Ao Vivo [IMPORT]", .Genre = genres.Single(Function(g) g.Name = "Latin"), .Price = 8.99D, .Artist = artists.Single(Function(a) a.Name = "Zeca Pagodinho"), .AlbumArtUrl = "/Content/Images/placeholder.gif"}}
        TempList.ForEach(Function(a) context.Albums.Add(a))
    End Sub
End Class